name: Generate Ethereum Private Key

on:
  push:
    branches: [ master ]

jobs:
  generate-private-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install ethers

      - name: Generate private key
        run: node .github/generate-private-key.js
        id: generate-private-key
          
      - name: Print private key and account address
        run: |
          echo "Private key: ${{ steps.generate-private-key.outputs.private_key }}"
          echo "Account address: ${{ steps.generate-private-key.outputs.account_address }}"